pipeline {
    agent any
    stages {
        stage('Build mysecond') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test mysecond') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver mysecond') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
    post {
        always {
            echo "Job now complete for this branch."
        }
    }
}
